
name: GitHub Actions Publish to PyPi
run-name: Publish to PyPi
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:

      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.ref, 'main')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      